config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :farms do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [ :show, :destroy ]
  get 'bookings/:id/accept', to: 'bookings#accept', as: :accept
  get 'bookings/:id/decline', to: 'bookings#decline', as: :decline
  get 'bookings', to: 'bookings#index'

  resources :profiles, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :farm
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings, dependent: :destroy

  validates :photo, presence: true
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :regions, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader

  REGIONS = ["Basse-Normandie", "Aquitaine", "Bourgogne", "Ile-de-France", "Champagne-Ardenne", "Picardie", "Haute-Normandie", "Centre", "Basse-Normandie", "Bourgogne", "Nord-Pas-de-Calais", "Lorraine", "Alsace", "Franche-Comté", "Pays de la Loire", "Bretagne", "Poitou-Charentes", "Aquitaine", "Midi-Pyrénées", "Limousin", "Rhône-Alpes", "Auvergne"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :farms, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # validates :photo, presence: true
  validates :name, presence: true
  validates :email, format: /@/
  validates :age, presence: true, allow_nil: true
  validates :location, presence: true, allow_nil: true
  validates :about, presence: true, allow_nil: true

  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end



  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo, :age, :location, :about])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo, :age, :location, :about])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.accepted = "Accepté"
    @booking.save
    redirect_to booking_path(@booking)
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.accepted = "Refusé"
    @booking.save
    redirect_to booking_path(@booking)
  end

  def new
    @farm = Farm.find(params[:farm_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.farm = Farm.find(params[:farm_id])
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to farm_path(@booking)
      # render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to farms_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :number_of_people, :message)
  end

end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    @farms = policy_scope(Farm).order(created_at: :desc)
    authorize @farms

    @farms = @farms.where(regions: params[:query]) if params[:query].present?

    @farms = @farms.where.not(latitude: nil, longitude: nil)
    @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @booking = Booking.new
    @farm = Farm.find(params[:id])
    authorize @farm
    authorize @booking
  end

  def new
    @farm = Farm.new
    authorize @farm
  end

  def create
    @farm = Farm.new(farms_params)
    @farm.user = current_user
    authorize @farm
    if @farm.save
      redirect_to farm_path(@farm)
    else
      render :new
    end
  end

  def edit
    @farm = Farm.find(params[:id])
    authorize @farm
  end

  def update
    @farm = Farm.find(params[:id])
    @farm.update(farms_params)
    authorize @farm
    redirect_to farm_path(@farm)
  end

  def destroy
    @farm = Farm.find(params[:id])
    authorize @farm
    @farm.destroy
    redirect_to farms_path
  end

  private

  def farms_params
    params.require(:farm).permit(:name, :address, :zip_code, :city, :photo, :description, :ovin, :caprin, :bovin, :size, :regions)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  skip_after_action :verify_authorized

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to booking.farm.name, booking_path(booking) %>
    </li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<h1 style="text-align: center; margin-top: 30px; margin-bottom: 30px;">Détails de ma réservation</h1>
<%= simple_form_for [@farm, @booking] do |f| %>
<div class="container-padded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-content">
        <div class="form-inputs" >
          <%= f.input :start_time %>
          <%= f.input :end_time %>
          <%= f.input :number_of_people %>
          <%= f.input :message %>
          <%= f.button :submit,class: "button-very-green create-farm" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
  <div class="container-paddedd">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="form-content">
          <div class="form-inputs" >
              <h3>Statut de ma réservation</h3>
            <div class="status">
              <p><%= @booking.accepted %></p>
            </div>
            <div class="cancel-reservation">
              <%= link_to "Annuler la réservation", booking_path(@booking), method: :delete, class: "button-very-green" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<%# if @booking.accepted == "En attente" %>
  <%#= link_to "Accepter", accept_path(@booking), class: "status-accepted" %>
  <%#= link_to "Refuser", decline_path(@booking), class: "status-deleted" %>
<%#= end %>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/farms/edit.html.erb
<h1>Edit the farm</h1>

<%= simple_form_for @farm do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.button :submit %>
<% end %>

app/views/farms/index.html.erb
<!-- Layout code for grid + map -->
<% if @farms.empty? %>
  <div class="wrap">
    <h1 style="text-align: center; margin-top: 150px; margin-bottom: 30px;">Essaye encore, il n'y a aucun résultat pour la recherche
    <strong>
    <% params[:query].each do |param| %>
      "<%= param.to_s %>"
    <% end %>
    </strong>
    </h1>
    <div class="container-padded">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <div class="form-content">
            <%= form_tag farms_path, method: :get do %>
              <%= label_tag "Choisissez votre région" %>
              <%= select_tag "query[]", options_for_select(Farm::REGIONS, params[:query]), multiple: true, class: "form-control select2 hello" %>
              <%= submit_tag "Valider", class: "edit_button button-very-green", id: "button-submit", style: "margin-top:30px;" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="map-layout">
    <div class="cards-container">
      <div class="submited-farm">
        <%= form_tag farms_path, method: :get do %>
          <%= label_tag "Choisissez votre région" %>
          <%= select_tag "query[]", options_for_select(Farm::REGIONS, params[:query]), multiple: true, class: "form-control select2 hello" %>
          <%= submit_tag "Valider", class: "edit_button button-very-green", id: "button-submit" %>
        <% end %>
      </div>
      <div class="row">
        <% @farms.each do |farm| %>
          <div class="col-xs-12 col-md-6 col-xl-4">
            <div class="farm-card">
              <div class="top-card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url('<%= cl_image_path farm.photo, crop: :fill %>');">
                <div class="hidden-hover">
                  <h3><%= farm.city %></h3>
                  <h5><%= farm.regions %></h5>
                </div>
                <div class="card-hover">
                  <p><%= farm.description[0..320] %>...</p>
                </div>
              </div>
              <div class="bottom-card">
                <%= image_tag farm.user.photo, crop: :fill, class: "small-avatar-circle" %>
                <%= link_to farm.name, farm_path(farm) %>
                <ul class="list-inline">
                  <li><i class="fa fa-share"></i></li>
                  <li><i class="fa fa-heart"></i></li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="map-container hidden-mobile">
      <div id="map" data-markers="<%= @markers.to_json %>"></div>
    </div>
  </div>
<% end %>

app/views/farms/new.html.erb
<h1 style="text-align: center; margin-top: 30px; margin-bottom: 30px;">Ma ferme</h1>
<%= simple_form_for @farm do |f| %>
<div class="container-padded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-content">
        <div class="form-inputs" >
          <%= f.input :name, label: "Nom" %>
          <%= f.input :address, label: "Adresse" %>
          <%= f.input :city, label: "Ville" %>
          <%= f.input :regions, collection: Farm::REGIONS, label: "Region" %>
          <%= f.input :description, label: "Description" %>
          <label for="">Types d'élevage (plusieurs choix possibles)</label>
          <div class="categories">
            <%= f.input :ovin %>
            <%= f.input :bovin %>
            <%= f.input :caprin %>
          </div>
          <%= f.input :size, label: "Taille de votre ferme (en  mètres carrés)" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, class: "button-very-green create-farm" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/farms/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.6)),
         url('<%= cl_image_path @farm.photo, crop: :fill %>'); background-size: cover; background-position: center; height: 55vh; ">
  <h1><%= @farm.name %></h1>
  <p><%= @farm.city %></p>
</div>

<div class="farm-show-layout">
  <div class="farm-info">
    <div class="pres-show-farm">
      <p>
        <%= link_to profile_path(@farm.user) do %>
          <%= image_tag @farm.user.photo, class: "big-avatar-circle" %>
        <% end %>
      </p>
      <p><%= @farm.user.name %></p>
    </div>
    <div class="description-farm-show">
      <p><%= @farm.description %></p>
      <div>
        <p>Informations complémentaires :</p>
          <li>Superficie de notre ferme : <%= @farm.size %>m2</li>
          <li>Contactez nous : <%= @farm.user.email %></li>
          </br>
      </div>
    </div>
  </div>

  <div class="reservation">
    <%= simple_form_for [@farm, @booking] do |f| %>
      <div class="form-content">
        <div class="form-inputs" >
          <%= f.input :start_time %>
          <%= f.input :end_time %>
          <%= f.input :number_of_people %>
          <%= f.input :message %>
          <%= f.button :submit,class: "button-very-green create-farm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ma ferme éphémère</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <% if user_signed_in? && current_page?('/') %>
      <%= render 'shared/navbar_connected' %>
    <% elsif current_page?('/') %>
      <%= render 'shared/navbar_home' %>
    <% elsif !user_signed_in? %>
      <%= render 'shared/navbar_not_connected' %>
    <% else user_signed_in? %>
      <%= render 'shared/navbar_connected' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <div class="page-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.4) 50%), url('https://images.unsplash.com/photo-1455348734739-11d7726c3c80?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=788e1f8cb2f36883bba6b2ad79ba6dca&auto=format&fit=crop&w=1267&q=80');">
  <div class="banner-content">
    <h1>Ma ferme éphémère</h1>
    <p>Expérimentez la vie à la ferme</p>
    <%= link_to "Découvrir", farms_path, class: "white-to-green-button btn-lg" %>
  </div>
</div>
<!-- ajout de la value proposition ici -->
<div class="wrapper">
  <div class="container">
  <h1>Quelques témoignages</h1>
    <div class="row">
      <div class ="col-xs-12 col-sm-6 col-md-4 desc">
        <div class="description">
          <div class="image">
            <%= image_tag "fermier1.jpeg", class: "big-avatar-circle fit" %>
          </div>
          <div class="content">
            <h2>"Une aventure humaine"</h2>
            <p>Grace à Ma ferme éphémère, j'ai pu partager le quotidien de personnes passionnantes qui souhaitaient partager leur expertise.</p>
          </div>
        </div>
      </div>
      <div class ="col-xs-12 col-sm-6 col-md-4 desc">
        <div class="description">
          <div class="image">
            <%= image_tag "fermier2.jpeg", class: "big-avatar-circle fit" %>
          </div>
          <div class="content">
            <h2>"Une très belle expérience"</h2>
            <p>Avoir l'opportunité de passer quelques jours en dehors de la ville avec les animaux, voir comment ça marche, et échanger avec les personnes... c'est génial!</p>
          </div>
        </div>
      </div>
      <div class ="col-xs-12 col-sm-6 col-md-4 desc">
        <div class="description">
          <div class="image">
            <%= image_tag "fermier3.jpeg", class: "big-avatar-circle fit" %>
          </div>
          <div class="content">
            <h2>"Des échanges et des rires"</h2>
            <p>S'occuper d'animaux domestiques n'est pas toujours facile, et voir des gens s'occuper toute la journée d'animaux de la basse-cour, ça fait du bien.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-farm">
          <div class="card-photo" style="background-image: linear-gradient(rgba(175,249,201,0.2), rgba(47,91,113,0.8)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
            <div class="card-infos">
              <h1>Ferme de Roger</h1>
              <p>Normandie, Calvados (14)</p>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
            <a class="card-link" href="#" ></a>
          </div>
          <div class="card-bottom">
            <p>Située au milieu des bocages Normands, Roger est prêt à vous recevoir quand vous le souhaitez</p>
            <div class="card-bottom-picto">
              <p>Categories</p>
              <p>
               <i class="far fa-star"></i>
               <i class="far fa-star"></i>
               <i class="far fa-star"></i>
               <i class="far fa-star"></i>
               <i class="far fa-star"></i>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-farm">
          <div class="card-photo" style="background-image: linear-gradient(rgba(175,249,201,0.2), rgba(47,91,113,0.8)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
            <div class="card-infos">
              <h1>Ferme de Roger</h1>
              <p>Normandie, Calvados (14)</p>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
            <a class="card-link" href="#" ></a>
          </div>
          <div class="card-bottom">
            <p>Située au milieu des bocages Normands, Roger est prêt à vous recevoir quand vous le souhaitez</p>
            <div class="card-bottom-picto">
              <p>Categories</p>
              <p>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-farm">
          <div class="card-photo" style="background-image: linear-gradient(rgba(175,249,201,0.2), rgba(47,91,113,0.8)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
            <div class="card-infos">
              <h1>Ferme de Pierre</h1>
              <p>Normandie, Calvados (14)</p>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
            <a class="card-link" href="#" ></a>
          </div>
          <div class="card-bottom">
            <p>Située au milieu des bocages Normands, Roger est prêt à vous recevoir quand vous le souhaitez</p>
            <div class="card-bottom-picto">
              <p>Categories</p>
              <p>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 -->

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<h1 style="text-align: center; margin-top: 30px; margin-bottom: 30px;"><%= @user.name %></h1>
<%= image_tag @user.photo, class: "big-avatar-circle" %>

<h2>Infos de l'utilisateur</h2>
<ul>
  <li> <%= @user.email %></li>
  <li> Membre depuis <%= @user.created_at %></li>
</ul>

<h3>Mes fermes</h3>
<ul> <% @user.farms.each do |farm| %>
  <li><%= farm.name %>
    <% if policy(farm).update? %>
        <%= link_to 'Edit', edit_farm_path(farm) %>
      <% end %>

      <% if policy(farm).destroy? %>
        <%= link_to 'Delete', farm, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %></li>
  <% end %>
</ul>

<h3>Mes réservations</h3>
<ul> <% @user.bookings.each do |booking| %>
  <li><%= booking.farm.name %> |
    <% if policy(booking).create? %>
      <%= booking.accepted %>
    <% end %>
  </li>
  <% end %>
</ul>

<h3>Les demandes de réservations sur mes fermes</h3>
<ul> <% @user.farms.each do |farm| %>
  <li> <%= farm.name  %>
      <% farm.bookings.each do |booking| %>
      <% if booking.accepted == "En attente" %>
          <% if policy(farm).update? %>
            <%= link_to "Accepter", accept_path(booking) %>
            <%= link_to "Refuser", decline_path(booking) %>
          <% end %>
        <% end %>
    <% end %>
  </li>
  <% end %>
</ul>


<%= link_to "Edit profile", edit_user_registration_path  %>

app/views/profiles/show.html.erb
<!-- <h1 style="text-align: center; margin-top: 30px; margin-bottom: 30px;">Toutes mes réservations</h1> -->
<div class="wrapper">
  <div class="container container-profile">
    <div class="flex-container">
      <div class="left-stuff">
        <div class="card-profile profile">
          <div class="card-content">
            <%= image_tag @user.photo, class: "big-avatar-circle" %>
            <h4><%= @user.name %></h4>
            <p><%= @user.age %> ans</p>
            <p><%= @user.location %> </p>
            <p>Membre depuis <%= @user.created_at %></p>
            <br>
            <% if current_user.farms.first.nil? %>
              <%= link_to "Ajouter une ferme", new_farm_path , class: "button-very-green" %>
            <% else %>
              <%= link_to "Ma ferme", farm_path(current_user.farms.first), class: "button-very-green"%>
            <% end %>
          </div>
        </div>
        <div class="card-profile kpi">
          <div class="card-content">
            <p><%= @user.about %></p>
          </div>
        </div>
      </div>
      <div class="right-stuff">
        <div class="card-profile description-profile">
          <h1>Réservations</h1>


          <% @user.bookings.each do |booking| %>

            <ul class="inbox">
              <li class="message">
                <div class="photo-and-name">
                  <%= image_tag booking.farm.user.photo, class: "small-avatar-circle" %>
                  <br>
                  <%= booking.farm.user.name %>
                </div>

                <div class="farm-name">
                  <%= booking.farm.name %>
                  <%= Time.now.strftime("%d/%m/%Y") %>
                </div>

                <div class="message-body">
                  <%= booking.message %>
                </div>
                <div class="message-status">
                  <p>Status</p>
                  <% if policy(booking).create? %>
                      <%= booking.accepted %>
                    <% end %>
                </div>
              </li>
            </ul>
          <% end %>


          <% @user.farms.each do |farm| %>
            <ul class="inbox">
              <% farm.bookings.each do |booking| %>
                <li class="message">

                  <div class="photo-and-name">
                    <%= image_tag booking.user.photo, class: "small-avatar-circle" %>
                    <%= booking.user.name %>
                  </div>
                  <div class="farm-name">
                    <%= farm.name  %>
                    <%= Time.now.strftime("%d/%m/%Y") %>
                  </div>
                  <div class="message-body">
                    <%= booking.message %>
                  </div>
                  <div class="message-status">
                    <% if booking.accepted == "En attente" %>
                      <% if policy(farm).update? %>
                        <%= link_to "Accepter", accept_path(booking) %>
                        <%= link_to "Refuser", decline_path(booking) %>
                      <% end %>
                    <% else %>
                      <%= booking.accepted %>
                    <% end %>
                  </div>
                <% end %>
              </li>
            </ul>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar_connected.html.erb
<div class="navbar">
  <div>
    <a href="/"><%= image_tag "logo2.png", class: "logo-3" %></a>
  </div>
  <div class="navbar-menu">
    <div class="add-farm">
      <%= link_to "Ajouter une ferme", new_farm_path, class: "navbar-menu-item" %>
    </div>
    <div class="msg">
      <%= link_to "Mes réservations", profile_path(current_user), class: "navbar-menu-item"  %>
    </div>
    <div class="navbar-menu-item-dropdown">
      <div class="dropdown">
        <%= image_tag(current_user.photo, class: "avatar dropdown-toggle small-avatar-circle", data: {toggle: "dropdown"}, id: "navbar-wagon-menu") %>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><%= link_to "Profil", profile_path(current_user),  class: "navbar-menu-item-dropdown"  %></li>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, method: "delete", class: "navbar-menu-item-dropdown"  %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/bookings.html.erb
<h1>Bookings</h1>
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to booking.farm.name, booking_path(booking) %>
    </li>
  <% end %>
</ul>